/* ===== Dummy Data for Development ===== */
import type { HeroContent, Service, Project, TeamMember, Testimonial, AboutContent, SiteSettings } from '@/types/database'

export const dummySettings: SiteSettings = {
  id: '1',
  site_name: 'Bico Creative',
  logo_url: null,
  favicon_url: null,
  contact_email: 'hello@bicocreative.com',
  contact_phone: '+62 812 3456 7890',
  contact_address: 'Jl. Sudirman No. 123, Jakarta Selatan, Indonesia 12190',
  working_hours: 'Mon - Fri: 09:00 - 18:00 WIB',
  social_links: {
    instagram: 'https://instagram.com/bicocreative',
    linkedin: 'https://linkedin.com/company/bicocreative',
    behance: 'https://behance.net/bicocreative',
    dribbble: 'https://dribbble.com/bicocreative',
  },
  updated_at: new Date().toISOString(),
}

export const dummyHero: HeroContent = {
  id: '1',
  heading: 'We Craft Digital Experiences That Matter',
  subheading: 'Bico Creative adalah agency kreatif yang membantu brand Anda tampil menonjol di dunia digital. Dari strategi hingga eksekusi, kami wujudkan visi Anda.',
  cta_primary_text: 'Mulai Proyek',
  cta_primary_link: '/contact',
  cta_secondary_text: 'Lihat Portfolio',
  cta_secondary_link: '/projects',
  background_image_url: null,
  client_logos: [
    { name: 'TechCorp', logo_url: '' },
    { name: 'StartupID', logo_url: '' },
    { name: 'GreenLeaf', logo_url: '' },
    { name: 'UrbanStyle', logo_url: '' },
    { name: 'DataFlow', logo_url: '' },
    { name: 'CloudNine', logo_url: '' },
  ],
  is_active: true,
  updated_at: new Date().toISOString(),
}

export const dummyServices: Service[] = [
  {
    id: '1',
    title: 'Brand Identity & Strategy',
    short_description: 'Bangun identitas brand yang kuat dan memorable. Dari logo hingga brand guideline yang komprehensif.',
    full_description: 'Kami membantu Anda membangun identitas brand yang tidak hanya indah, tapi juga strategis. Setiap elemen visual dirancang dengan tujuan — mulai dari logo, tipografi, palet warna, hingga brand guideline lengkap yang memastikan konsistensi di semua touchpoint.',
    icon: 'Palette',
    image_url: null,
    features: ['Logo Design', 'Brand Guidelines', 'Visual Identity System', 'Brand Strategy', 'Stationery Design'],
    sort_order: 0,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'UI/UX Design',
    short_description: 'Desain antarmuka yang intuitif dan pengalaman pengguna yang memikat. Research-driven dan user-centered.',
    full_description: 'Tim desainer kami menerapkan pendekatan user-centered design untuk menciptakan antarmuka yang tidak hanya cantik, tapi juga mudah digunakan. Dari riset pengguna hingga prototyping interaktif, kami memastikan setiap pixel memiliki tujuan.',
    icon: 'Figma',
    image_url: null,
    features: ['User Research', 'Wireframing', 'Interactive Prototyping', 'Usability Testing', 'Design System'],
    sort_order: 1,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'Web Development',
    short_description: 'Website modern, cepat, dan responsif. Dibangun dengan teknologi terkini untuk performa optimal.',
    full_description: 'Kami membangun website dan web application menggunakan stack teknologi modern. Fokus pada performa, aksesibilitas, dan skalabilitas — memastikan produk digital Anda siap untuk pertumbuhan.',
    icon: 'Code',
    image_url: null,
    features: ['Responsive Website', 'Web Application', 'CMS Development', 'E-Commerce', 'API Integration'],
    sort_order: 2,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    title: 'Digital Marketing',
    short_description: 'Strategi digital marketing yang terukur dan efektif. Dari SEO hingga social media management.',
    full_description: 'Kami merancang dan mengeksekusi strategi digital marketing yang data-driven. Setiap campaign dioptimalkan untuk memberikan ROI maksimal dan pertumbuhan yang berkelanjutan untuk bisnis Anda.',
    icon: 'TrendingUp',
    image_url: null,
    features: ['SEO Optimization', 'Social Media Management', 'Content Strategy', 'Google Ads', 'Analytics & Reporting'],
    sort_order: 3,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    title: 'Motion & Video',
    short_description: 'Konten visual yang dinamis dan engaging. Motion graphics dan video production berkualitas tinggi.',
    full_description: 'Dari motion graphics hingga video production, kami menciptakan konten visual yang menarik perhatian dan menyampaikan pesan brand Anda dengan powerful. Setiap frame dirancang untuk membuat dampak.',
    icon: 'Video',
    image_url: null,
    features: ['Motion Graphics', 'Video Production', 'Animation', 'Social Media Video', 'Explainer Video'],
    sort_order: 4,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const dummyProjects: Project[] = [
  {
    id: '1',
    title: 'TechCorp Brand Refresh',
    description: 'Redesign identitas visual lengkap untuk perusahaan teknologi terkemuka. Mencakup logo baru, brand guideline, dan implementasi di seluruh touchpoint digital.',
    category: 'Branding',
    client_name: 'TechCorp Indonesia',
    thumbnail_url: null,
    gallery_images: [],
    project_url: 'https://techcorp.id',
    tech_stack: ['Figma', 'Illustrator', 'After Effects'],
    is_featured: true,
    sort_order: 0,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'GreenLeaf E-Commerce',
    description: 'Platform e-commerce untuk brand fashion sustainable. UI/UX design dan full-stack development dengan fokus pada pengalaman belanja yang seamless.',
    category: 'Development',
    client_name: 'GreenLeaf Fashion',
    thumbnail_url: null,
    gallery_images: [],
    project_url: 'https://greenleaf.co.id',
    tech_stack: ['React', 'Next.js', 'Tailwind CSS', 'Supabase'],
    is_featured: true,
    sort_order: 1,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'UrbanStyle App Design',
    description: 'Desain aplikasi mobile untuk platform lifestyle dan fashion. Pengalaman pengguna yang personal dan engaging.',
    category: 'Web Design',
    client_name: 'UrbanStyle',
    thumbnail_url: null,
    gallery_images: [],
    project_url: null,
    tech_stack: ['Figma', 'Protopie', 'Principle'],
    is_featured: true,
    sort_order: 2,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    title: 'DataFlow Dashboard',
    description: 'Dashboard analytics real-time untuk SaaS platform. Visualisasi data yang kompleks dibuat sederhana dan actionable.',
    category: 'Development',
    client_name: 'DataFlow Analytics',
    thumbnail_url: null,
    gallery_images: [],
    project_url: 'https://dataflow.io',
    tech_stack: ['React', 'TypeScript', 'D3.js', 'Node.js'],
    is_featured: true,
    sort_order: 3,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    title: 'StartupID Campaign',
    description: 'Digital marketing campaign untuk peluncuran produk startup fintech. Strategi multi-channel yang menghasilkan 300% increase in sign-ups.',
    category: 'Marketing',
    client_name: 'StartupID',
    thumbnail_url: null,
    gallery_images: [],
    project_url: null,
    tech_stack: ['Google Ads', 'Meta Ads', 'Analytics'],
    is_featured: false,
    sort_order: 4,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    title: 'CloudNine Motion Reel',
    description: 'Motion graphics showreel dan explainer video series untuk cloud computing company. Visual storytelling yang menyederhanakan konsep teknis.',
    category: 'Motion',
    client_name: 'CloudNine Tech',
    thumbnail_url: null,
    gallery_images: [],
    project_url: null,
    tech_stack: ['After Effects', 'Cinema 4D', 'Premiere Pro'],
    is_featured: false,
    sort_order: 5,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const dummyTeam: TeamMember[] = [
  {
    id: '1',
    name: 'Andi Prasetyo',
    role: 'Founder & Creative Director',
    bio: 'Dengan pengalaman lebih dari 10 tahun di industri kreatif, Andi memimpin visi dan arah kreatif Bico Creative.',
    photo_url: null,
    social_links: { linkedin: '#', dribbble: '#' },
    sort_order: 0,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Sarah Wijaya',
    role: 'Head of Design',
    bio: 'Sarah menggabungkan estetika dan fungsionalitas dalam setiap desain. Ahli dalam UI/UX dan brand identity.',
    photo_url: null,
    social_links: { linkedin: '#', behance: '#' },
    sort_order: 1,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Rizky Nugroho',
    role: 'Lead Developer',
    bio: 'Full-stack developer yang passionate dengan clean code dan performant web applications.',
    photo_url: null,
    social_links: { linkedin: '#', github: '#' },
    sort_order: 2,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Maya Putri',
    role: 'Digital Strategist',
    bio: 'Data-driven marketer dengan track record dalam campaign performance optimization.',
    photo_url: null,
    social_links: { linkedin: '#', instagram: '#' },
    sort_order: 3,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const dummyTestimonials: Testimonial[] = [
  {
    id: '1',
    quote: 'Bico Creative benar-benar memahami visi kami. Hasil kerja mereka melampaui ekspektasi — brand kami terlihat jauh lebih profesional dan modern.',
    author_name: 'Diana Kusuma',
    author_role: 'CEO',
    company: 'TechCorp Indonesia',
    author_photo_url: null,
    rating: 5,
    sort_order: 0,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    quote: 'Tim yang sangat responsif dan kreatif. Website yang mereka bangun membantu kami meningkatkan konversi hingga 200%. Highly recommended!',
    author_name: 'Budi Santoso',
    author_role: 'Marketing Director',
    company: 'GreenLeaf Fashion',
    author_photo_url: null,
    rating: 5,
    sort_order: 1,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    quote: 'Proses kerja yang terstruktur dan transparan. Setiap milestone dikomunikasikan dengan baik. Kolaborasi yang menyenangkan!',
    author_name: 'Putri Maharani',
    author_role: 'Product Manager',
    company: 'DataFlow Analytics',
    author_photo_url: null,
    rating: 5,
    sort_order: 2,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const dummyAbout: AboutContent = {
  id: '1',
  heading: "We're Bico Creative",
  description: 'Bico Creative adalah agency kreatif berbasis di Jakarta yang berdiri sejak 2018. Kami percaya bahwa desain yang baik bukan hanya soal estetika — tapi juga tentang strategi, cerita, dan dampak nyata bagi bisnis klien kami. Dengan tim yang terdiri dari desainer, developer, dan strategist berpengalaman, kami telah membantu puluhan brand Indonesia tampil memukau di dunia digital.',
  mission: 'Memberdayakan brand Indonesia dengan solusi kreatif digital yang inovatif, strategis, dan berdampak. Kami berkomitmen menghadirkan karya berkualitas tinggi yang mendorong pertumbuhan bisnis klien.',
  vision: 'Menjadi agency kreatif digital terdepan di Indonesia yang dikenal karena keunggulan desain, inovasi teknologi, dan dampak nyata bagi setiap brand yang kami sentuh.',
  image_url: null,
  core_values: [
    { title: 'Kreativitas Tanpa Batas', description: 'Kami selalu mencari cara baru dan segar untuk menyelesaikan setiap tantangan kreatif.' },
    { title: 'Kolaborasi Erat', description: 'Kami percaya hasil terbaik lahir dari kolaborasi yang transparan dan terbuka dengan klien.' },
    { title: 'Kualitas di Atas Segalanya', description: 'Setiap detail penting. Kami tidak berkompromi dengan kualitas dalam setiap deliverable.' },
  ],
  stats: [
    { label: 'Projects Completed', value: '150+' },
    { label: 'Happy Clients', value: '80+' },
    { label: 'Years of Experience', value: '7+' },
    { label: 'Awards Won', value: '12' },
  ],
  updated_at: new Date().toISOString(),
}
